# Generated by Django 4.1.3 on 2022-11-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAnimeList',
            fields=[
                ('Anime_id', models.AutoField(primary_key=True, serialize=False)),
                ('Anime_Name', models.CharField(max_length=10000)),
            ],
        ),
    ]
